import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "infinity coders",
  description: "infinity coders is a platform for event management.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "event organizer",
    "event organiser",
    "shadcn",
    "shadcn-ui",
    "radix-ui",
    "cn",
    "clsx",
    "uploadthing",
    "date-fns",
    "stripe",
    "clerk",
    "usehooks-ts",
    "mongodb",
    "mongoose",
    "nosql",
    "prisma",
    "lucide-react",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "infinity codersa Kumar Verma",
    url: "https://github.com/infinity codersy",
  },
} as const;
